services:
  - type: web
    name: inventory-app
    plan: free
    dockerfilePath: ./Dockerfile
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: prod

      - key: DB_HOST
        fromDatabase:
          name: inventory-db
          property: host

      - key: DB_PORT
        fromDatabase:
          name: inventory-db
          property: port

      - key: DB_DATABASE
        fromDatabase:
          name: inventory-db
          property: database

      - key: SPRING_DATASOURCE_USERNAME
        fromDatabase:
          name: inventory-db
          property: user

      - key: SPRING_DATASOURCE_PASSWORD
        fromDatabase:
          name: inventory-db
          property: password
    runtime: docker

databases:
  - name: inventory-db
    plan: free